-- Assignment: JOIN Operations for E-commerce
-- Date: 14-07-2026
-- Tech Stack: SQL
-- Topic: JOINs

-- =========================
-- Table Creation
-- =========================

CREATE TABLE Customers (
    customer_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    phone_number VARCHAR(20),
    address TEXT,
    date_joined DATE
);

CREATE TABLE Orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    total_amount DECIMAL(10,2),
    shipping_address TEXT,
    payment_status VARCHAR(20),
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
);

CREATE TABLE Categories (
    category_id INT PRIMARY KEY,
    category_name VARCHAR(50),
    description TEXT
);

CREATE TABLE Products (
    product_id INT PRIMARY KEY,
    name VARCHAR(100),
    description TEXT,
    price DECIMAL(10,2),
    stock_quantity INT,
    category_id INT,
    FOREIGN KEY (category_id) REFERENCES Categories(category_id)
);

CREATE TABLE Order_Items (
    order_item_id INT PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT,
    item_price DECIMAL(10,2),
    FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    FOREIGN KEY (product_id) REFERENCES Products(product_id)
);

-- =========================
-- 20 JOIN Queries
-- =========================

-- 1. Orders made by a specific customer
SELECT c.first_name, c.last_name, o.order_id, o.order_date, o.total_amount
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
WHERE c.customer_id = 101;

-- 2. Orders placed by customers from a specific city
SELECT c.first_name, c.address, o.order_id, o.order_date
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
WHERE c.address LIKE '%Hyderabad%';

-- 3. Products and their categories
SELECT p.name AS product_name, c.category_name
FROM Products p
JOIN Categories c ON p.category_id = c.category_id;

-- 4. Products purchased by a particular customer
SELECT cu.first_name, p.name, p.description, oi.quantity
FROM Customers cu
JOIN Orders o ON cu.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
WHERE cu.customer_id = 101;

-- 5. Products ordered with total amount
SELECT o.order_id, oi.product_id, oi.quantity, o.total_amount
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id;

-- 6. Total number of items ordered per product
SELECT p.name, SUM(oi.quantity) AS total_items
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.name;

-- 7. Customer who placed the highest value order
SELECT c.first_name, c.last_name, o.total_amount
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
ORDER BY o.total_amount DESC
LIMIT 1;

-- 8. Customers who ordered a specific product
SELECT DISTINCT c.first_name, c.last_name, p.name
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
WHERE p.name = 'Laptop';

-- 9. Total revenue generated by each product
SELECT p.name, SUM(oi.item_price * oi.quantity) AS total_revenue
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY p.name;

-- 10. Most popular product in each category
SELECT c.category_name, p.name, SUM(oi.quantity) AS total_sold
FROM Categories c
JOIN Products p ON c.category_id = p.category_id
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY c.category_name, p.name
ORDER BY total_sold DESC;

-- 11. Orders with product details
SELECT o.order_id, p.name, oi.quantity
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id;

-- 12. Average number of items ordered per customer
SELECT c.customer_id, c.first_name, AVG(oi.quantity) AS avg_items
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id;

-- 13. Customers with no orders
SELECT c.customer_id, c.first_name, c.last_name
FROM Customers c
LEFT JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;

-- 14. Orders with more than 5 items
SELECT o.order_id, c.first_name, c.last_name, SUM(oi.quantity) AS total_items
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Customers c ON o.customer_id = c.customer_id
GROUP BY o.order_id
HAVING total_items > 5;

-- 15. Total products sold per category
SELECT cat.category_name, SUM(oi.quantity) AS total_sold
FROM Categories cat
JOIN Products p ON cat.category_id = p.category_id
JOIN Order_Items oi ON p.product_id = oi.product_id
GROUP BY cat.category_name;

-- 16. Orders placed in last 30 days
SELECT o.order_id, o.order_date, p.name, oi.quantity
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
JOIN Products p ON oi.product_id = p.product_id
WHERE o.order_date >= CURDATE() - INTERVAL 30 DAY;

-- 17. Out-of-stock products previously ordered
SELECT DISTINCT p.name, p.stock_quantity
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
WHERE p.stock_quantity = 0;

-- 18. Products not sold in last 6 months
SELECT p.name
FROM Products p
LEFT JOIN Order_Items oi ON p.product_id = oi.product_id
LEFT JOIN Orders o ON oi.order_id = o.order_id
WHERE o.order_date < CURDATE() - INTERVAL 6 MONTH OR o.order_date IS NULL;

-- 19. Customers with orders above a threshold
SELECT c.first_name, c.last_name, o.order_id, o.total_amount
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
WHERE o.total_amount > 5000;

-- 20. Total sales amount per customer
SELECT c.customer_id, c.first_name, c.last_name, SUM(oi.item_price * oi.quantity) AS total_sales
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
GROUP BY c.customer_id;
